### PR TITLE
Update with 5.6.0.ER2 build

### PR DESCRIPTION
**Pull request by mdrafiur**

### CODE REVIEW

**Comment by bekionel** [comment]
Hi @mdrafiur , with https://github.com/jboss-container-images/jboss-webserver-5-image/pull/33 it seems that you don't require a separate branch for openj9 any more, so this PR might be obsolete. Please let me know what you prefer after you've synced with @levivic and we can proceed accordingly, thanks.

**Comment by levivic** [comment]
@mdrafiur i have restructured the way we build jws image. In the future, we will not need openj9 branch. Instead we will have a j9 override file. see https://github.com/jboss-container-images/jboss-webserver-5-image/pull/33

@bekionel do you want to remove the webserver56-openj9-rhel8 branch, since we won't need it anymore?

**Comment by levivic** [comment]
@bekionel maybe lets keep this branch alive until the images built using the other method is tested perfectly fine.

**Comment by bekionel** [comment]
@levivic @mdrafiur sure, works for me. Merging.

**Pull request merged**
